### ISSUE TITLE
Change config format?

### ISSUE THREAD

**Issue by 0xbrayo** [ActivityWatch/aw-tauri#129]
I don't like the current config file format, specifically the duplicated `[[autostart_modules]]` sections. Seems unintuitive to users who have never seen a `.toml` file before

```toml
[defaults]
autostart = true
autostart_minimized = true
port = 5600
discovery_paths = ["/home/brayo/aw-modules"]

[[autostart_modules]]
name = "aw-awatcher"
args = ""

[[autostart_modules]]
name = "aw-watcher-lastfm"
args = ""

[[autostart_modules]]
name = "aw-work-sync"
args = ""

[[autostart_modules]]
name = "aw-watcher-media-player"
args = ""

[[autostart_modules]]
name = "aw-sync"
args = "daemon"
```

Thinking of simplifying it to something like.

```toml
[defaults]
autostart = true
autostart_minimized = true
port = 5600
discovery_paths = ["/home/brayo/aw-modules"]

[autostart_modules]
modules = [
  { name = "aw-awatcher", args = "" },
  { name = "aw-watcher-lastfm", args = "" },
  { name = "aw-work-sync", args = "" },
  { name = "aw-watcher-media-player", args = "" },
  { name = "aw-sync", args = "daemon" }
]
```
